apiVersion: v1
kind: Secret
metadata:
  name: sta-spring-boot-trading-agent-oauth2
type: Opaque
stringData:
  provider: sandbox
  type: oauth2
  client-authentication-method: client_secret_basic
  authorization-grant-types: client_credentials
  scope: bid
  client-id: sta_springkles
  client-secret: e0e993cc-2828-4cf0-b9fd-8c13e96831b0
  issuer-uri: https://login.sso.az.run.withtanzu.com
